config/routes.rb
User::Application.routes.draw do
  resources :myusers

end

app/models/myuser.rb
class Myuser < ActiveRecord::Base
  has_attached_file :avatar, {
    :styles => {
      :thumb => ["50x50#", :png],
      :medium => ["100x100#", :png],
      :large => ["300x300>", :png]
    },
    :convert_options => {
      :thumb => "-gravity Center -crop 50x50+0+0",
      :thumb => "-gravity Center -crop 100x100+0+0",
    }
  }
  validates_attachment_content_type :avatar, :content_type => %w(image/jpeg image/jpg image/png)

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/myusers_controller.rb
class MyusersController < ApplicationController
  before_action :set_myuser, only: [:show, :edit, :update, :destroy]

  # GET /myusers
  # GET /myusers.json
  def index
    @myusers = Myuser.all
  end

  # GET /myusers/1
  # GET /myusers/1.json
  def show
  end

  # GET /myusers/new
  def new
    @myuser = Myuser.new
  end

  # GET /myusers/1/edit
  def edit
  end

  # POST /myusers
  # POST /myusers.json
  def create
    @myuser = Myuser.new(myuser_params)

    respond_to do |format|
      if @myuser.save
        format.html { redirect_to @myuser, notice: 'Myuser was successfully created.' }
        format.json { render action: 'show', status: :created, location: @myuser }
      else
        format.html { render action: 'new' }
        format.json { render json: @myuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /myusers/1
  # PATCH/PUT /myusers/1.json
  def update
    respond_to do |format|
      if @myuser.update(myuser_params)
        format.html { redirect_to @myuser, notice: 'Myuser was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @myuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /myusers/1
  # DELETE /myusers/1.json
  def destroy
    @myuser.destroy
    respond_to do |format|
      format.html { redirect_to myusers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_myuser
      @myuser = Myuser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def myuser_params
      params.require(:myuser).permit(:uname , :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/myusers_helper.rb
module MyusersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>User</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/myusers/_form.html.erb
<%= form_for(@myuser) do |f| %>
  <% if @myuser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@myuser.errors.count, "error") %> prohibited this myuser from being saved:</h2>

      <ul>
      <% @myuser.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uname %><br>
    <%= f.text_field :uname %>
  </div>


<div class="avatar">
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
    </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/myusers/edit.html.erb
<h1>Editing myuser</h1>

<%= render 'form' %>

<%= link_to 'Show', @myuser %> |
<%= link_to 'Back', myusers_path %>

app/views/myusers/index.html.erb
<h1>Listing myusers</h1>

<table>
  <thead>
    <tr>
      <th>Uname</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @myusers.each do |myuser| %>
      <tr>
        <td><%= myuser.uname %></td>
        <td><%= link_to 'Show', myuser %></td>
        <td><%= link_to 'Edit', edit_myuser_path(myuser) %></td>
        <td><%= link_to 'Destroy', myuser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Myuser', new_myuser_path %>

app/views/myusers/new.html.erb
<h1>New myuser</h1>

<%= render 'form' %>

<%= link_to 'Back', myusers_path %>

app/views/myusers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uname:</strong>
  <%= @myuser.uname %>

</p>



<div class="avatar">
    <%= image_tag @myuser.avatar(:medium) %>
  </div>


<%= link_to 'Edit', edit_myuser_path(@myuser) %> |
<%= link_to 'Back', myusers_path %>